# https://stackoverflow.com/a/68213855/16484891
# CC BY-SA 4.0

name: Sync with subrepo
run-name: syyynnnc with subrepo

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 283375/test-repo
          ref: "master"
          token: ${{ secrets.ACTIONS_SYNC_SUBMODULE_TEST }}
          submodules: true

      - name: setup git config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: sync submodules
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - name: commit
        run: |
          git add --all
          git commit -m "theme: update test subrepo"
          git push
